### ISSUE TITLE
Internal server error when joining server

### ISSUE THREAD

**Issue by Hounddraco** [Stereowalker/C.O.M.B.A.T.#10]
When I try to join a server with the mod install the game doesn't crash but I always get an internal server error  have this happens on forge 28.1.39 and 28.1.44

**Comment by Stereowalker** [comment]
I'll work on it

**Comment by Hounddraco** [comment]
ok

**Comment by Stereowalker** [comment]
Check now. Although, you cant use the "N" and "B" keys to swap spells anymore. If you want to swap spells, you now have to sneak and click. Enjoy

**Comment by Hounddraco** [comment]
I'll check it out now and get back to you

**Comment by Hounddraco** [comment]
Works fine thanks for the help
