### ISSUE TITLE
Resource heavy?

### ISSUE THREAD

**Issue by CherubAgent1440** [Stereowalker/C.O.M.B.A.T.#11]
Is COMBAT resource heavy, or is it a low-poly, high fps mod even on a potato pc?
I would like to run it on a server, and, though my pc is BEAST, my friend's pc is a potato. Also, is it optifine compatible?

Sorry if this shouldn't be an issue, but I am not sure where to put it.

**Comment by Stereowalker** [comment]
Your friends potato pc should be able to handle it. I normally use the mod with optifine and I haven't come across any issues.
