### ISSUE TITLE
Mana

### ISSUE THREAD

**Issue by CherubAgent1440** [Stereowalker/C.O.M.B.A.T.#12]
Is there a way to view your Mana? And is their a way to give yourself infinite mana (disable mana checking)?

Sorry that this is in Issues, I can't login to curseforge for some reason (and so can't post comments).

**Comment by Stereowalker** [comment]
Yes, in survival you should see a bar above your health. As for the infinite mana, I can probably make it work, though you'd have to wait a while

**Comment by Stereowalker** [comment]
As per your request, You can set mana to infinite in your world in the configs
