### ISSUE TITLE
client connecting to server(1.14.4) C.O.M.B.A.T.-1.14.4-0.25.0.jar

### ISSUE THREAD

**Issue by SDUBZ** [Stereowalker/C.O.M.B.A.T.#14]
Forge :1.14.4-90

combat on server and client: C.O.M.B.A.T.-1.14.4-0.25.0.jar

[19:11:27] [Netty Epoll Server IO #2/ERROR] [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [combat:main] rejected their client side version number
[19:11:27] [Netty Epoll Server IO #2/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Terminating connection with client, mismatched mod list

**Comment by SDUBZ** [comment]
Server logs:
[debug.log](https://github.com/Stereowalker/C.O.M.B.A.T./files/3854908/debug.log)
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T./files/3854909/latest.log)

Client logs:
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T./files/3854910/latest.log)

**Comment by Stereowalker** [comment]
Can you give me your mod list, and have you tried using the mod by itself

**Comment by SDUBZ** [comment]
it was working before its not since the new version

**Comment by Stereowalker** [comment]
I'm not too sure of what to make of the issue since there are a lot of mods. Why don't you try creating a new server with only the mod in it to verify if the problem is really  from the mod

**Comment by Stereowalker** [comment]
Apparently the fault was on my end, I've uploaded a fix

**Comment by SDUBZ** [comment]
thank you
