### ISSUE TITLE
[Forge 1.14.4][Client thread/FATAL] [combat/]: NetworkPlayerInfo of %s is null(player cant join anymore to dedicated server

### ISSUE THREAD

**Issue by SDUBZ** [Stereowalker/C.O.M.B.A.T.#17]
Forge:1.14.4-99/96
Combat version: C.O.M.B.A.T.-1.14.4-0.28.0
logs: https://gist.github.com/SDUBZ/56d7a371660f9ced6dcb6c70c3514dc7
this happens after rejoining and playing after one day

**Comment by Stereowalker** [comment]
Please report back if your still receiving errors after the update

**Comment by SDUBZ** [comment]
okay i will do hopefully what ever you did fixes this  thank you for your work

**Comment by SDUBZ** [comment]
yes this is still happening after update

**Comment by Stereowalker** [comment]
Try 1.0.1

**Comment by SDUBZ** [comment]
will do

**Comment by SDUBZ** [comment]
well i wish i could http://puu.sh/EPXrf/b1a467caad.png you are sending too much nbt

**Comment by Stereowalker** [comment]
Disable capes. Its what's causing the issue

**Comment by SDUBZ** [comment]
i will try and get back to you

**Comment by SDUBZ** [comment]
nope still over sized packet

**Comment by Stereowalker** [comment]
You used to use this mod without this issue before right?

**Comment by SDUBZ** [comment]
yeah now all of a sudden its over sending packet sizes

**Comment by Stereowalker** [comment]
I've made an attempt to remove a few of the features I've added a few updates ago
