### ISSUE TITLE
Tridox Isn't dropping anything

### ISSUE THREAD

**Issue by poboy975** [Stereowalker/C.O.M.B.A.T.#2]
I've tried every pickaxe in the game, in a creative world, and nothing drops from mining tridox.
![modlist1 14 3](https://user-images.githubusercontent.com/249487/61016902-f4bc3200-a356-11e9-995f-fad4b4562cdf.jpg)

**Comment by Stereowalker** [comment]
Thanks for informing me about the issue.

**Comment by Stereowalker** [comment]
I''ll upload an update addressing the issue within 18 hours of this comment

**Comment by Stereowalker** [comment]
I've uploaded it. Tridox ore should drop tridox when mined with an iron pickaxe now
