### ISSUE TITLE
A TileEntity type com.stereowalker.combat.tileentity.ConnectorTIleEntity has thrown and exception trying to write state. It will not persist, Report this to the mod author

### ISSUE THREAD

**Issue by Gamerbolts** [Stereowalker/C.O.M.B.A.T.#20]
Hello! I am creating a modpack and came across this issue. It doesn't seem to be affecting my modpack in any way but wanted to bring it up to you since that is what the log said to do.

Here is the image of the log that posted in my console on the server:
https://imgur.com/a/GEPF7mI

And here is the full log:
[latest.log](https://github.com/Stereowalker/C.O.M.B.A.T./files/4124502/latest.log)

Thank you in advanced for your help!

**Comment by Stereowalker** [comment]
I've stopped updating 1.14.4 so I can't really help with that
