### ISSUE TITLE
[1.15.2] (Feature Request) Please add an option to enable and disable each ore and perfentages.

### ISSUE THREAD

**Issue by ProsperCraft** [Stereowalker/C.O.M.B.A.T.#21]
I have 8 types of copper ore and I want the ore from a different mod, please add the option to disable individual ores, I can't toggle all ores or we will miss out on your special ores.

Modpack - https://www.curseforge.com/minecraft/modpacks/towncraft     2

**Comment by Stereowalker** [comment]
Alright

**Comment by Stereowalker** [comment]
I've added the option to disable specific ores
