### ISSUE TITLE
Change keybindings according to the conventions

### ISSUE THREAD

**Issue by PT400C** [Stereowalker/C.O.M.B.A.T.#22]
Hey,

C O M B A T causes a mayor problem with my mod [DefaultSettings](https://minecraft.curseforge.com/projects/defaultsettings). 

The reason is that your mod creates keybinds like this: `key.combat:next_spell`. In fact it should be `key.combat.next_spell`

Thanks in advance

PT400C

**Comment by Stereowalker** [comment]
That shouldn't be a problem

**Comment by PT400C** [comment]
@Stereowalker For Minecraft it isn't. But as DefaultSettings is based off the standard naming, it doesn't expect two double colons per keybind. But since there are two, it fails parsing the name properly.

**Comment by Stereowalker** [comment]
Well, I've changed them to the standard naming so DefaultSettings shouldn't have an issue with parsing C.O.M.B.A.T. keybinds
