### ISSUE TITLE
Incompatibility with Biomes O'Plenty

### ISSUE THREAD

**Issue by GrifVindh** [Stereowalker/C.O.M.B.A.T.#4]
When both C.O.M.B.A.T. and Biomes O'Plenty are installed, it is not possible to choose BOP as a terrain type when creating a new world. It also seems to generate a crash when the Default terrain type is selected.

To reproduce:

1. Install both C.O.M.B.A.T. and Biomes O'Plenty

2. Start Minecraft, go to main screen.

3. Select Create New World

4. Select More World Options...

5. Click on World Type to cycle through all the terrain options.

Biomes O'Plenty will not appear as an option.

If you remove COMBAT, the BOP option appears again.

**Comment by Stereowalker** [comment]
what version of BOP, COMBAT and Forge did you use.

**Comment by GrifVindh** [comment]
Sorry for the delay in responding!

C.O.M.B.A.T.-1.14.4-0.12.3.jar
BiomesOPlenty-1.14.4.-9.0.0.229-universal.jar, I think (it's been on a rather rapid release schedule for 1.14.4)
forge-1.14.4-28.0.45-installer.jar

**Comment by Stereowalker** [comment]
Try running it again with C.O.M.B.A.T.-1.14.4-0.14.1.jar

**Comment by GrifVindh** [comment]
With the latest version of everything (Forge 1.14.4-28.0.55, BOP 1.14.4-0.0.0.231, and C.O.M.B.A.T. 1.14.4-0.15.0) BOP shows up as a world type again.

**Comment by Stereowalker** [comment]
Thats good to know
