### ISSUE TITLE
Disables JEI

### ISSUE THREAD

**Issue by FunZone513** [Stereowalker/C.O.M.B.A.T.#6]
JEI doesn't show up
searching for recipes using keybinds doesn't work either

not sure what else to say here.

doesn't seem to error or anything it just removes JEI outright

**Comment by Stereowalker** [comment]
You could start by giving more details to your problem like whether running JEI without C.O.M.B.A.T. seemed to solve the issue, the versions of Forge, JEI and C.O.M.B.A.T. and whether or not you ran other mods alongside JEI and C.O.M.B.A.T.

**Comment by Feed4mylife** [comment]
My JEI also doesnt work. After it didnt Show up i removed C.O.M.B.A.T it worked again

**Comment by FunZone513** [comment]
latest forge: 28.0.95
only jei and combat active, jei disabled
remove combat, jei is fine
