### ISSUE TITLE
Multiplayer Server won't start

### ISSUE THREAD

**Issue by Hounddraco** [Stereowalker/C.O.M.B.A.T.#8]
[crash-2019-10-02_22.54.54-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T./files/3684363/crash-2019-10-02_22.54.54-server.txt)

**Comment by Stereowalker** [comment]
Let's ask the important questions first, what version of forge and combat are you using

**Comment by Hounddraco** [comment]
I am using forge 28.0.106 and the most recent version of The mod I also just tested it with forge 28.1.39

**Comment by Stereowalker** [comment]
Thanks for your support. I should be able to have a fix within 24 hours. When you see the update, attempt to recreate the crash and give me your feedback

**Comment by Stereowalker** [comment]
Hold up, did it give out the same error when you updated to 28.1.39

**Comment by Hounddraco** [comment]
i'll send the error report
[crash-2019-10-08_07.40.38-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T./files/3705086/crash-2019-10-08_07.40.38-server.txt)

**Comment by Stereowalker** [comment]
Alright, checkout 0.23.0 and give me your feedback

**Comment by Hounddraco** [comment]
with forge 28.0.106
[crash-2019-10-10_20.52.24-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T./files/3715288/crash-2019-10-10_20.52.24-server.txt)

**Comment by Hounddraco** [comment]
with forge 28.1.39
[crash-2019-10-10_20.53.51-server.txt]
(https://github.com/Stereowalker/C.O.M.B.A.T./files/3715292/crash-2019-10-10_20.53.51-server.txt)

**Comment by Stereowalker** [comment]
try it now with 0.23.1. I believe i've fixed whatever issues were in the crash report.

**Comment by Hounddraco** [comment]
ok

**Comment by Hounddraco** [comment]
[crash-2019-10-11_14.35.25-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T./files/3719362/crash-2019-10-11_14.35.25-server.txt)
[crash-2019-10-11_14.34.23-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T./files/3719364/crash-2019-10-11_14.34.23-server.txt)

**Comment by Stereowalker** [comment]
Check 0.23.2. I'm confident that it should work now

**Comment by Hounddraco** [comment]
it works
