### ISSUE TITLE
Client crash before running MC

### ISSUE THREAD

**Issue by ImperatorEdi** [Stereowalker/C.O.M.B.A.T.#9]
Hello, 
I have Forge 1.14.4 - 28.1.0 (Recommended).

Crash Report:
[ttps://pastebin.com/raw/21iL68tw](https://pastebin.com/raw/21iL68tw)

Game crashed before starting and loading.

**Comment by Stereowalker** [comment]
Update forge to 1.14.4-28.1.40.

**Comment by Stereowalker** [comment]
Is it working now?

**Comment by ImperatorEdi** [comment]
Is ok, sorry and thanks.
